### ISSUE TITLE
Throws an error while initiation

### ISSUE THREAD

**Issue by abhi18av** [hails/slides-com-downloader#1]
Hi @hails ,

I really wanted to download a slide from `slides.com` and found your project - thanks for this project man ;) 

The problem is when I tried using it, there seems to be a `promise` relaated error. Could you please look into it?

```
(anaconda3-2019.03) (base) Abhinavs-MacBook-Pro:slides-com-downloader eklavya$ node ./index.js https://slides.com/verythorough/ddd-wtd#/
Downloading slides from: https://slides.com/verythorough/ddd-wtd#/
(node:8606) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_closeCallback' of undefined
    at close (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/puppeteer/lib/Browser.js:255:16)
    at /Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/puppeteer/lib/helper.js:111:23
    at tryCatcher (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/eklavya/projects/work/Pesto/_slides/slides-com-downloader/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:8606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C(anaconda3-2019.03) (base) Abhinavs-MacBook-Pro:slides-com-downloader eklavya$
```

**Comment by hails** [comment]
Hey @abhi18av 
Gonna take a look into that, thanks!

**Comment by hails** [comment]
@abhi18av it should be working now!
Mind updating from master and testing again?

**Comment by abhi18av** [comment]
Whoops, so sorry I forgot to update on this. Yup it working like a charm. Thanks! 👍
